apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-service
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      restartPolicy: Always
      containers:
      - name: myapp
        image: raniantouni/kafka-producer:1.0.0
        ports:
        - containerPort: 3001
